language: node_js
node_js:
  - "12"
dist: trusty
sudo: required

branches:
  only:
  - master
  
cache:
  yarn: true

before_script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.4
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn global add @angular/cli


script:
  - ng lint
  - npm run test-headless
  - ng build --prod --base-href https://github.com/shubham-it-chd/v1/

